language: node_js
node_js:
- 10
- 8
- 6
before_install:
- curl -o- -L https://yarnpkg.com/install.sh
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
install: yarn --ignore-engines
before_script: greenkeeper-lockfile-update
script:
- yarn commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"
- yarn commitlint --from=$TRAVIS_COMMIT
- yarn prettylint
- yarn test --coverage --maxWorkers 2
after_script: greenkeeper-lockfile-upload
jobs:
  include:
  - stage: danger
    node_js: 8
    os: linux
    script:
    - npx -p danger@^3 danger ci
  - stage: release
    node_js: lts/*
    os: linux
    after_success: npx semantic-release@15
cache:
  yarn: true
branches:
  only:
  - master
  # Practical when batching releases
  - next
  - "/^greenkeeper/.*$/"
env:
  global:
  - BUILD_LEADER_ID=6
  - GK_LOCK_YARN_OPTS="--ignore-engines"
  - secure: HN9UwIwZ0NIOgGaRHssKraQy5L4q0Jagtq4nsw75vUHmrc2tNYCpqREtIr7DlapurtVpXsOd5G8FiVMN6YWQA1WVuvoTD7AqJOXYF72gtSnIJ+mER6a4fFQe+2cPMu8l6/jYAFDzQ/ZJqd7QM8DZu6siYAmiJqmq1OmUSP3aohn/bCwyKcvD8MybNQvYvB9j1YzcypbE1LFUeV0oQX8rt9F+5PgY0vB/JE+X806sepgdv8LiVAfy2D/4IhHE55QtC1dfKsCl7Sn1nVriD16Z+OwsabQnp61wptOxaOsHM41eaXd1YlRyqYM1czNoFqgPMyo8uycSO/c7zl5cxWadZmvl21aZXHkb2HTH/XKP6BaZAa7DHwt1S2M8tP9YLDwhO24kSbxRA53Eiqnx+i3kgqsE+g2/XN7dMZpJ3MKgxyXB/dMC1G9qORGs1HdBgDIs4PXP4RMssXpntYJ+QW5JN/cByyA/K90V4K+QV9I4kVVBIXYvTyoyaTj/DwCXwC0zzU+F0BDcTHLtndFvJw6LND/WcYYKTJvwP0glPD/7okPtjYXzWMYPC0jkazLc85g31YvKDvfIel+OJ0j3Z/d2mbekIrL4j1+OSGv2rqSVaLT2H+QUO2WJaYvP8J0ITBVRSp5TopJL9Td9OOhIG/t6FxgKRDnKmoK3647NzcY4TFI=
  - secure: 0FGgH7QexQVaqpuuVL8KYy+dxgOAsGHsmormi04P8VaidKvq+kKkKlYm9bh6EkCypLh256+OReETQbfRiCiTqtiJx058t9Jvra8PRPYbCk/Rjx62QALdbvrgWnBPEfpj5Ko8xtu5hjIQtgcw0WWHcfJbJy4tU6MCXMxqo4QyCzO1tJ5JWfULILA7bB+Yu5RGW3YbABGoL3PWKvjuXaJcZdafxpV6h/z4w75McdSffctlbkTHgpfvS5k6DQ56DB1fdUAFEm2C65xlr9JAaoM71Z4r2DDe/zDY+qr9fPaVorRB6fZ+gt7d8n57DeDkzZLiDJjlUOTyL42q3jEIRe9+M8a3CwwXon8CCW4/S+rzMnk0SF1UXExYzoYY/KJnw486M9xLpdXZXOLNXWZ1o0NnM18qo4pm0G2CHs44thxvePVjXB386UBy8pk6m/w5VUBEHTHpUlL1/bLNYai65M4Fly/7ufnkxKE0Y081mMT6W/jL3x2gc15hTJ9UV0QYiVp8jXwksBJVAHFuFTX3BuFdWRWnyDhiBdH6XTz6rvY1Kpen7tca+vqdGcCt4MtjRzSWg+1+VyefUC+42oTnLqYZ9Kjmtrk+8zAEXDP1SDjuyiwLkBN4HZDZP7+zDzgibGuA/gZUDNdKN6cA09JikcV0GlNFWKz3o2S048KBTjV9luU=
